table achievement
	isHidden
	lineageTag: c27cdb71-823f-4fea-af2d-e0226fa50def

	measure 'News Last Achievement Obtained' =
			
			VAR IDLastAch = [Last Achievement Unlocked ID]
			VAR DateLastAch = [Last Achievement Unlock Max Date]
			RETURN
			CALCULATE(CONCATENATE(MAX('Ref Achievements'[name]),CONCATENATE(" : ", MAX('Ref Achievements'[description]))), 'Ref Achievements'[apiname] = IDLastAch)
		lineageTag: 6ff213a8-2c9f-4256-bd22-36ec2c80a492

		annotation PBI_FormatHint = {"isText":true}

	measure 'News Last Achievement Pic' =
			
			VAR LastAchID = [Last Achievement Unlocked ID]
			RETURN
			CALCULATE(MAX('Ref Achievements'[iconClosed]), 'Ref Achievements'[apiname] = LastAchID)
		lineageTag: 13381efe-e4aa-4323-ab39-deff3aaa2890
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isText":true}

	measure 'Best Achievement obtained' =
			
			VAR BestID = [Obtained rarest achievement]
			RETURN
			CALCULATE(CONCATENATE(MAX('Ref Achievements'[name]),CONCATENATE(" : ", MAX('Ref Achievements'[description]))), 'Ref Achievements'[apiname] = BestID)
		lineageTag: 03ec14f1-896c-4915-9103-dd3238174f1a

		annotation PBI_FormatHint = {"isText":true}

	measure 'Best Achievement obtained Pic' =
			
			VAR BestID = [Obtained rarest achievement]
			RETURN
			CALCULATE(MAX('Ref Achievements'[iconClosed]), 'Ref Achievements'[apiname] = BestID)
		lineageTag: f9da878f-f295-4b24-aff7-6d31adc985e1
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isText":true}

	measure 'Unobtained most common achievement rate' =
			
			VAR REF = VALUES('Ref Achievements'[apiname])
			VAR LIST = VALUES('List Achievements'[apiname])
			RETURN
			CALCULATE([Most obtained achievement rate], EXCEPT(REF,LIST))
		lineageTag: 1a3f2d5a-7012-4ce7-ba76-cbaa0e67cd00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Worst Achievement not obtained' =
			
			VAR WorstID = [Unobtained most common achievement]
			RETURN
			CALCULATE(CONCATENATE(MAX('Ref Achievements'[name]),CONCATENATE(" : ", MAX('Ref Achievements'[description]))), 'Ref Achievements'[apiname] = WorstID)
		lineageTag: 51aef916-e96a-4864-a080-1e9073544079

		annotation PBI_FormatHint = {"isText":true}

	measure 'Worst Achievement not obtained pic' =
			
			VAR WorstID = [Unobtained most common achievement]
			RETURN
			CALCULATE(MAX('Ref Achievements'[iconOpen]), 'Ref Achievements'[apiname] = WorstID)
		lineageTag: 4855a4f5-ef5f-44e4-9443-78323147b49f
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isText":true}

	measure 'Obtained Rarest achievement rate' =
			
			VAR REF = VALUES('Ref Achievements'[apiname])
			VAR LIST = VALUES('List Achievements'[apiname])
			RETURN
			CALCULATE([Least obtained achievement rate], INTERSECT(REF,LIST))
		lineageTag: d321be04-f07b-4333-ab21-f6c621aa3fab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column name
		dataType: string
		isHidden
		lineageTag: 4dab5b71-eaf8-459a-954c-fef136650002
		summarizeBy: none
		sourceColumn: name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column percent
		dataType: double
		isHidden
		lineageTag: 16ff21bc-fb66-4257-b11b-6a104d18f69c
		summarizeBy: sum
		sourceColumn: percent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition achievement-fc020647-0e07-4b8a-abf5-d0054981c754 = m
		mode: import
		source =
				let
				    Source = Xml.Tables(Web.Contents("http://api.steampowered.com/ISteamUserStats/GetGlobalAchievementPercentagesForApp/v0002/?gameid=582010&format=xml")),
				    Table0 = Source{0}[Table],
				    Table1 = Table0{0}[Table],
				    #"Valeur remplacée" = Table.ReplaceValue(Table1,".",",",Replacer.ReplaceText,{"percent"}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Valeur remplacée",{{"percent", type number}}),
				    #"Texte en minuscules" = Table.TransformColumns(#"Type modifié",{{"name", Text.Lower, type text}})
				in
				    #"Texte en minuscules"

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/achievement/Texte en minuscules.{name,0}","Section1/achievement/Type modifié.{percent,1}"],"ColumnCount":2,"KeyColumnNames":[],"ColumnIdentities":["Section1/achievement/Texte en minuscules.{name,0}","Section1/achievement/Type modifié.{percent,1}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

