table 'Ben Achievements'
	lineageTag: 7ecd166e-fec0-4f97-ad1d-82020c62e0f5

	measure 'Nb Achievements' = COUNTA('List Achievements'[apiname])
		formatString: 0
		lineageTag: e6cdc9cd-4e6e-4a65-8319-899752ff6f31

	measure 'Hours played last 2 weeks' = MAX('List Achievements'[hoursPlayed])
		lineageTag: 40d05426-125e-44df-b65e-ba6b10904a3e

		annotation PBI_FormatHint = {"isText":true}

	column steamID64
		dataType: string
		lineageTag: cf5b7638-68f1-425f-b489-4d65d218b9a2
		summarizeBy: none
		sourceColumn: steamID64

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column hoursPlayed
		dataType: string
		lineageTag: c5a61a92-6a8d-4333-b146-d6780af41656
		summarizeBy: none
		sourceColumn: hoursPlayed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column apiname
		dataType: string
		lineageTag: 90f560d0-5ac6-4f06-bceb-daac77645175
		summarizeBy: none
		sourceColumn: apiname

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column unlockTimestamp
		dataType: int64
		formatString: 0
		lineageTag: 9435f6ca-c272-4c66-883d-0590fc49aeb0
		summarizeBy: sum
		sourceColumn: unlockTimestamp

		annotation SummarizationSetBy = Automatic

	column Attribute:closed
		dataType: string
		lineageTag: e6cadda3-8dc5-456c-9b5c-6c93e877c79b
		summarizeBy: none
		sourceColumn: Attribute:closed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column DateUnlock
		dataType: dateTime
		formatString: General Date
		lineageTag: e7250f47-0a10-432e-b65d-ed2d041fd808
		summarizeBy: none
		sourceColumn: DateUnlock

		variation Variation
			isDefault
			relationship: b60c954b-1ed0-422a-b202-0a6074f6395b
			defaultHierarchy: LocalDateTable_759ef156-f7d2-49ca-bcc3-429cbd4e5054.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 0e9f1924-7f8d-4a23-94c7-7cb684cf89b9
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition 'Ben Achievements-b21eab76-12cc-476b-b2e6-d9d84fb886cd' = m
		mode: import
		source =
				let
				    Source = Xml.Tables(Web.Contents("https://steamcommunity.com/profiles/76561198160709063/stats/582010/achievements/?xml=1")),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"privacyState", type text}, {"visibilityState", Int64.Type}}),
				    #"game développé" = Table.ExpandTableColumn(#"Type modifié", "game", {"gameFriendlyName", "gameName", "gameLink", "gameIcon", "gameLogo", "gameLogoSmall"}, {"game.gameFriendlyName", "game.gameName", "game.gameLink", "game.gameIcon", "game.gameLogo", "game.gameLogoSmall"}),
				    #"player développé" = Table.ExpandTableColumn(#"game développé", "player", {"steamID64", "customURL"}, {"steamID64", "customURL"}),
				    #"stats développé" = Table.ExpandTableColumn(#"player développé", "stats", {"hoursPlayed"}, {"hoursPlayed"}),
				    #"achievements développé" = Table.ExpandTableColumn(#"stats développé", "achievements", {"achievement"}, {"achievement"}),
				    #"achievement développé" = Table.ExpandTableColumn(#"achievements développé", "achievement", {"iconClosed", "iconOpen", "name", "apiname", "description", "unlockTimestamp", "Attribute:closed"}, {"iconClosed", "iconOpen", "name", "apiname", "description", "unlockTimestamp", "Attribute:closed"}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"achievement développé",{"privacyState", "visibilityState", "game.gameFriendlyName", "game.gameName", "game.gameLink", "game.gameIcon", "game.gameLogo", "game.gameLogoSmall", "customURL", "iconClosed", "iconOpen", "name", "description"}),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Colonnes supprimées",{{"unlockTimestamp", Int64.Type}}),
				    #"Lignes filtrées" = Table.SelectRows(#"Type modifié1", each ([unlockTimestamp] <> null)),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Lignes filtrées", "DateUnlock", each #datetime(1970,1,1,0,0,0)+#duration(0,0,0,[unlockTimestamp])),
				    #"Type modifié2" = Table.TransformColumnTypes(#"Personnalisée ajoutée",{{"DateUnlock", type datetime}}),
				    #"Personnalisée ajoutée1" = Table.AddColumn(#"Type modifié2", "Name", each "Ben")
				in
				    #"Personnalisée ajoutée1"

	annotation PBI_QueryRelationships = {"columnCount":7,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Ben Achievements/player développé.{steamID64,8}","Section1/Ben Achievements/stats développé.{hoursPlayed,10}","Section1/Ben Achievements/achievement développé.{apiname,14}","Section1/Ben Achievements/Type modifié1.{unlockTimestamp,3}","Section1/Ben Achievements/achievement développé.{Attribute:closed,17}","Section1/Ben Achievements/Type modifié2.{DateUnlock,5}","Section1/Ben Achievements/Personnalisée ajoutée1.{Name,6}"],"ColumnCount":7,"KeyColumnNames":[],"ColumnIdentities":["Section1/Ben Achievements/player développé.{steamID64,8}","Section1/Ben Achievements/stats développé.{hoursPlayed,10}","Section1/Ben Achievements/achievement développé.{apiname,14}","Section1/Ben Achievements/Type modifié1.{unlockTimestamp,3}","Section1/Ben Achievements/achievement développé.{Attribute:closed,17}","Section1/Ben Achievements/Type modifié2.{DateUnlock,5}","Section1/Ben Achievements/Personnalisée ajoutée1.{Name,6}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

