table 'Pierre Stats'
	isHidden
	lineageTag: d6a1c71f-51be-4de5-8b9a-8ea12ff372ed

	column name
		dataType: string
		isHidden
		lineageTag: eec25973-6767-40cd-9684-b182d2d56c75
		summarizeBy: none
		sourceColumn: name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column value
		dataType: string
		isHidden
		lineageTag: 8bc6863e-c79c-4e43-b5d0-d039a4e5316d
		summarizeBy: none
		sourceColumn: value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Player
		dataType: string
		isHidden
		lineageTag: 19a33e4e-4eeb-4980-8107-d7730b7c8c96
		summarizeBy: none
		sourceColumn: Player

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition 'Pierre Stats-f18f6606-629e-49f4-878b-07f80a356be5' = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("http://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0002/?appid=582010&key=3D71B244A257FE79DA02720E4AC449E2&steamid=76561198132862949")),
				    playerstats = Source[playerstats],
				    stats = playerstats[stats],
				    #"Converti en table" = Table.FromList(stats, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 développé" = Table.ExpandRecordColumn(#"Converti en table", "Column1", {"name", "value"}, {"name", "value"}),
				    #"Lignes filtrées" = Table.SelectRows(#"Column1 développé", each Text.Contains([name], "Weapon")),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Lignes filtrées", "Player", each "Pierre")
				in
				    #"Personnalisée ajoutée"

	annotation PBI_QueryRelationships = {"columnCount":3,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Pierre Stats/Column1 développé.{name,0}","Section1/Pierre Stats/Column1 développé.{value,1}","Section1/Pierre Stats/Personnalisée ajoutée.{Player,2}"],"ColumnCount":3,"KeyColumnNames":[],"ColumnIdentities":["Section1/Pierre Stats/Column1 développé.{name,0}","Section1/Pierre Stats/Column1 développé.{value,1}","Section1/Pierre Stats/Personnalisée ajoutée.{Player,2}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

