table 'Pierre Stats'
	isHidden
	lineageTag: 95598008-0ca9-4227-95a0-2ebad670099a

	column name
		dataType: string
		isHidden
		lineageTag: 7300a780-c4ff-455a-8d34-ae5f7e064527
		summarizeBy: none
		sourceColumn: name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column value
		dataType: string
		isHidden
		lineageTag: bb9696b3-ac5f-4c38-a03a-c8a4918b82de
		summarizeBy: none
		sourceColumn: value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Player
		dataType: string
		isHidden
		lineageTag: ab9f6dd9-bc5b-4739-89d0-9588afaf6cf6
		summarizeBy: none
		sourceColumn: Player

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition 'Pierre Stats-f18f6606-629e-49f4-878b-07f80a356be5' = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("http://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0002/?appid=582010&key=3D71B244A257FE79DA02720E4AC449E2&steamid=76561198132862949")),
				    playerstats = Source[playerstats],
				    stats = playerstats[stats],
				    #"Converti en table" = Table.FromList(stats, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 développé" = Table.ExpandRecordColumn(#"Converti en table", "Column1", {"name", "value"}, {"name", "value"}),
				    #"Lignes filtrées" = Table.SelectRows(#"Column1 développé", each Text.Contains([name], "Weapon")),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Lignes filtrées", "Player", each "Pierre")
				in
				    #"Personnalisée ajoutée"

	annotation PBI_QueryRelationships = {"columnCount":3,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Pierre Stats/Column1 développé.{name,0}","Section1/Pierre Stats/Column1 développé.{value,1}","Section1/Pierre Stats/Personnalisée ajoutée.{Player,2}"],"ColumnCount":3,"KeyColumnNames":[],"ColumnIdentities":["Section1/Pierre Stats/Column1 développé.{name,0}","Section1/Pierre Stats/Column1 développé.{value,1}","Section1/Pierre Stats/Personnalisée ajoutée.{Player,2}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

