table 'Ref Achievements'
	lineageTag: 13e806e7-978c-46a0-9c65-9501ded486f9

	column gameName
		dataType: string
		lineageTag: a005469d-c8fb-4298-8e29-e6a4ad8f62a5
		summarizeBy: none
		sourceColumn: gameName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column gameIcon
		dataType: string
		lineageTag: 9bb0e230-20dc-44bb-bcc8-b678d2319cf9
		summarizeBy: none
		sourceColumn: gameIcon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column gameLogo
		dataType: string
		lineageTag: 4f6e8244-2f81-4b58-bef1-eec98abb6a63
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: gameLogo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column gameLogoSmall
		dataType: string
		lineageTag: d72b92c8-5136-4748-accb-5ff26f55a593
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: gameLogoSmall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column iconClosed
		dataType: string
		lineageTag: ed62863f-5285-4da4-a20a-aa3d972d9319
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: iconClosed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column iconOpen
		dataType: string
		lineageTag: a75c07a1-fd55-4854-9494-88a84203eb5e
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: iconOpen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column name
		dataType: string
		lineageTag: 1cabf1ab-16e5-4840-abf1-69c78bdf11c7
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column apiname
		dataType: string
		lineageTag: 235621b7-9865-45e6-998e-9b1cffca8d11
		summarizeBy: none
		sourceColumn: apiname

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column description
		dataType: string
		lineageTag: dc5ac750-ea7d-406c-b5e0-ab90758c981d
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column percent
		dataType: double
		lineageTag: 50a5f869-7d4b-4e69-86f3-b1d114dd25ec
		summarizeBy: sum
		sourceColumn: percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Ref Achievements-c2859e14-7ffe-4cfd-9976-e7d697b41eb3' = m
		mode: import
		source =
				let
				    Source = Xml.Tables(Web.Contents("https://steamcommunity.com/profiles/76561198160709063/stats/582010/achievements/?xml=1")),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"privacyState", type text}, {"visibilityState", Int64.Type}}),
				    #"game développé" = Table.ExpandTableColumn(#"Type modifié", "game", {"gameFriendlyName", "gameName", "gameLink", "gameIcon", "gameLogo", "gameLogoSmall"}, {"gameFriendlyName", "gameName", "gameLink", "gameIcon", "gameLogo", "gameLogoSmall"}),
				    #"player développé" = Table.ExpandTableColumn(#"game développé", "player", {"steamID64", "customURL"}, {"steamID64", "customURL"}),
				    #"stats développé" = Table.ExpandTableColumn(#"player développé", "stats", {"hoursPlayed"}, {"hoursPlayed"}),
				    #"achievements développé" = Table.ExpandTableColumn(#"stats développé", "achievements", {"achievement"}, {"achievement"}),
				    #"achievement développé" = Table.ExpandTableColumn(#"achievements développé", "achievement", {"iconClosed", "iconOpen", "name", "apiname", "description", "unlockTimestamp", "Attribute:closed"}, {"iconClosed", "iconOpen", "name", "apiname", "description", "unlockTimestamp", "Attribute:closed"}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"achievement développé",{"privacyState", "visibilityState", "gameFriendlyName", "gameLink", "steamID64", "customURL", "hoursPlayed", "unlockTimestamp", "Attribute:closed"}),
				    #"Lignes triées" = Table.Sort(#"Colonnes supprimées",{{"apiname", Order.Ascending}}),
				    #"Requêtes fusionnées" = Table.NestedJoin(#"Lignes triées", {"apiname"}, achievement, {"name"}, "achievement", JoinKind.LeftOuter),
				    #"achievement développé1" = Table.ExpandTableColumn(#"Requêtes fusionnées", "achievement", {"percent"}, {"percent"})
				in
				    #"achievement développé1"

	annotation PBI_QueryRelationships = {"columnCount":10,"keyColumnNames":[],"queryRelationships":[{"keyColumnCount":1,"keyColumn":7,"otherKeyColumnIdentity":"Section1/achievement/Texte en minuscules.{name,0}","KeyColumnCount":1}],"columnIdentities":["Section1/Ref Achievements/game développé.{gameName,3}","Section1/Ref Achievements/game développé.{gameIcon,5}","Section1/Ref Achievements/game développé.{gameLogo,6}","Section1/Ref Achievements/game développé.{gameLogoSmall,7}","Section1/Ref Achievements/achievement développé.{iconClosed,11}","Section1/Ref Achievements/achievement développé.{iconOpen,12}","Section1/Ref Achievements/achievement développé.{name,13}","Section1/Ref Achievements/achievement développé.{apiname,14}","Section1/Ref Achievements/achievement développé.{description,15}","Section1/achievement/Type modifié.{percent,1}"],"ColumnCount":10,"KeyColumnNames":[],"ColumnIdentities":["Section1/Ref Achievements/game développé.{gameName,3}","Section1/Ref Achievements/game développé.{gameIcon,5}","Section1/Ref Achievements/game développé.{gameLogo,6}","Section1/Ref Achievements/game développé.{gameLogoSmall,7}","Section1/Ref Achievements/achievement développé.{iconClosed,11}","Section1/Ref Achievements/achievement développé.{iconOpen,12}","Section1/Ref Achievements/achievement développé.{name,13}","Section1/Ref Achievements/achievement développé.{apiname,14}","Section1/Ref Achievements/achievement développé.{description,15}","Section1/achievement/Type modifié.{percent,1}"],"RelationshipInfo":[{"keyColumnCount":1,"keyColumn":7,"otherKeyColumnIdentity":"Section1/achievement/Texte en minuscules.{name,0}","KeyColumnCount":1}]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

