table Stats
	lineageTag: 33fd101f-1475-4752-a66b-03eef9ebb778

	column name
		dataType: string
		lineageTag: 2704b607-b267-4243-9f4a-41cbc1138bb4
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column value
		dataType: int64
		formatString: 0
		lineageTag: edeb5170-2f40-49f4-95a6-768bb5c4ed08
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column Player
		dataType: string
		lineageTag: b7dd31ca-8ca7-49e1-880b-4b700f373978
		summarizeBy: none
		sourceColumn: Player

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Stats-295a0852-fe2a-4ae3-b4d6-e6b97aab8da6 = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Ben Stats", #"Rom Stats", #"Pierre Stats"}),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"value", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_QueryRelationships = {"columnCount":3,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Stats/Source.{name,0}","Section1/Stats/Type modifié.{value,1}","Section1/Stats/Source.{Player,2}"],"ColumnCount":3,"KeyColumnNames":[],"ColumnIdentities":["Section1/Stats/Source.{name,0}","Section1/Stats/Type modifié.{value,1}","Section1/Stats/Source.{Player,2}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

