table Mesures
	lineageTag: ac27f767-9816-4e0b-b49b-295026a86f57

	measure Revenu = SUMX(F_Productions, F_Productions[Durée]*F_Productions[TJM Reel])
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: ab01974a-50e2-46e1-b484-64ad0f4d4db4

	measure DeltaTJ = SUMX(F_Productions, F_Productions[TJM Cible]-F_Productions[TJM Reel])
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: f508866b-a9ed-41c3-922d-51dca426cb22

	measure TJM =
			
			VAR Ponderee = SUMX(F_Productions, F_Productions[TJM Reel]*F_Productions[Durée])
			VAR DureeTotale = SUM(F_Productions[Durée])
			    RETURN
			          DIVIDE(Ponderee,DureeTotale,0)
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 06ab1599-8ca6-4239-8d62-30e14e44ded7

	measure SumDurée = Sum(F_Productions[Durée])
		lineageTag: f184b96f-bcc1-4a2b-9d74-3478398ac3b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: b1cf1039-1f83-448b-99aa-a314d68521dd
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Mesures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = abb25ac3cb2b44e59765107676c38a93

